from typing import List, Optional
from app.salary.engine import SalarySummary


class ReplyService:
    """Formats clean, conversational, text-only WhatsApp replies for forwarding."""

    @staticmethod
    def format_payment_summary(summary: SalarySummary) -> str:
        lines = [
            f"📋 *SALARY PAYMENT SUMMARY*",
            f"━━━━━━━━━━━━━━━━━━",
            f"🗓️ *Month:* {summary.month_name}",
            f"👤 *Worker:* {summary.worker_name} ({summary.role})",
            f"💰 *Monthly Salary:* ₹{summary.monthly_salary:,.2f}",
            f"📅 *Working Days:* {summary.working_days} days",
            f"🧮 *Daily Rate:* ₹{summary.daily_rate:,.2f}/day",
            f"",
            f"❌ *Absent Days:* {summary.absent_days}",
            f"🌗 *Half Days:* {summary.half_days}",
            f"🏖️ *Planned Leave:* {summary.planned_leave_days}",
            f"",
            f"📉 *Deduction:* ₹{summary.total_deductions:,.2f}",
            f"💸 *Advance Paid:* ₹{summary.total_advances:,.2f}",
            f"🎁 *Bonus:* ₹{summary.total_bonuses:,.2f}",
            f"💵 *Already Paid:* ₹{summary.total_paid:,.2f}",
            f"━━━━━━━━━━━━━━━━━━",
            f"✅ *NET PAYABLE:* ₹{summary.net_payable:,.2f}",
            f"📌 *Status:* {summary.payment_status}",
        ]

        if summary.recent_events_summary:
            lines.append("")
            lines.append("📝 *Recent Events:*")
            lines.extend(summary.recent_events_summary[:5])

        lines.append("")
        lines.append("_Generated by HomeHelp AI Assistant_")
        return "\n".join(lines)

    @staticmethod
    def format_help() -> str:
        return (
            "👋 *Hello! I am HomeHelp AI*, your personal domestic worker salary assistant.\n\n"
            "Here is what you can tell or ask me:\n\n"
            "🔹 *Register Worker:* Add maid Sunita Salary 9000 Sunday off\n"
            "🔹 *Record Absent:* Sunita absent today\n"
            "🔹 *Record Half Day:* Sunita half day\n"
            "🔹 *Record Leave:* Sunita leave tomorrow\n"
            "🔹 *Record Advance:* Sunita took 500 advance\n"
            "🔹 *Record Bonus:* Bonus 1000 for Sunita\n"
            "🔹 *Record Payment:* Paid Sunita 7500\n"
            "🔹 *Update Salary:* Sunita salary is now 9500\n"
            "🔹 *Remove Worker:* Remove Sunita\n"
            "🔹 *Generate Payment:* Generate payment for Sunita\n\n"
            "You can send text messages or voice notes! 🎙️"
        )
